# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='agency',
            field=models.CharField(blank=True, max_length=255, verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_source',
            field=models.CharField(blank=True, max_length=255, verbose_name='Data source'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='stats_available',
            field=models.CharField(blank=True, max_length=50, verbose_name='Statistics are availble'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='target_description',
            field=models.TextField(blank=True, verbose_name='Target description'),
        ),
    ]
