# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0002_add_target_source_agency_and_stats_available_fields_to_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='slug',
        ),
    ]
