# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_remove_name_and_slug_on_indicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='value_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='stats_available',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No')], max_length=50, verbose_name='Statistics are availble'),
        ),
    ]
