# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 08:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_add_value_unit_on_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='value_unit',
            field=models.CharField(blank=True, max_length=50, verbose_name='Value unit'),
        ),
    ]
