# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0006_add_area_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/areas/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/components/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/goals/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='goals/indicators/images', verbose_name='Image'),
        ),
    ]
