# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_add_field_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='component',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
