# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 05:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0010_add_related_name_to_fks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='stats_available',
            field=models.CharField(blank=True, choices=[('YES', 'Yes'), ('NO', 'No'), ('PARTIALLY', 'Partially'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=50, verbose_name='Statistics availble'),
        ),
    ]
