# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 12:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0012_add_fields_target_value_and_value_unit_to_component'),
    ]

    operations = [
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Target number')),
                ('description', models.TextField(blank=True, verbose_name='Target description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='goals/targets/images', verbose_name='Image')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified')),
                ('extras', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}, null=True, verbose_name='Extras')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='goals.Goal', verbose_name='Goal')),
            ],
            options={
                'verbose_name_plural': 'Targets',
                'verbose_name': 'Target',
            },
        ),
    ]
