# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0014_add_field_target_to_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicator',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='target_description',
        ),
    ]
