# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-23 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0015_remove_fields_goal_and_target_description_from_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='target',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='goals.Target', verbose_name='Target'),
            preserve_default=False,
        ),
    ]
