# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-26 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0020_add_field_indicators_to_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='indicator',
        ),
    ]
