# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-27 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0021_remove_field_indicator_from_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Goal description'),
        ),
        migrations.AddField(
            model_name='goal',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Goal description'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/goals/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='goal',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/goals/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Goal name'),
        ),
        migrations.AddField(
            model_name='goal',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Goal name'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='agency_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='agency_sw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_source_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data source'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='data_source_sw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data source'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Indicator description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Indicator description'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/indicators/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/indicators/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/goals/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='plan',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/goals/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='target',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Target description'),
        ),
        migrations.AddField(
            model_name='target',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Target description'),
        ),
        migrations.AddField(
            model_name='target',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/targets/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='target',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/targets/images', verbose_name='Image'),
        ),
    ]
