# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 08:09
from __future__ import unicode_literals

from django.db import migrations, models


def add_target_names(apps, schema_editor):
    """Add Target names from Target descriptions.
    """
    from django.template.defaultfilters import truncatechars, slugify
    Target= apps.get_model('goals', 'Target')

    for target in Target.objects.iterator():
        target.name = truncatechars(target.description, 250)
        target.slug = slugify(target.name[:50])
        target.save()

def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0022_add_en_and_sw_model_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Target'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.RunPython(add_target_names, reverse_code=dummy),
    ]
