# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 08:59
from __future__ import unicode_literals

from django.db import migrations, models


def add_indicator_names(apps, schema_editor):
    """Add Indicator names from Indicator descriptions.
    """
    from django.template.defaultfilters import truncatechars, slugify
    Indicator = apps.get_model('goals', 'Indicator')

    for indicator in Indicator.objects.iterator():
        indicator.name = truncatechars(indicator.description, 250)
        indicator.slug = slugify(indicator.name[:50])
        indicator.save()

def dummy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0023_add_fields_name_and_slug_to_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Indicator'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
        migrations.RunPython(add_indicator_names, reverse_code=dummy),
    ]
