# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-29 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0026_move_agency_source_and_stats_available_fields_from_indicator_to_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Component name'),
        ),
        migrations.AddField(
            model_name='component',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Component name'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Indicator'),
        ),
        migrations.AddField(
            model_name='target',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Target'),
        ),
        migrations.AddField(
            model_name='target',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Target'),
        ),
    ]
