# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0028_add_null_constain_to_progress_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Area description'),
        ),
        migrations.AddField(
            model_name='area',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Area description'),
        ),
        migrations.AddField(
            model_name='area',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/areas/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='area',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/areas/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='area',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Area name'),
        ),
        migrations.AddField(
            model_name='area',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Area name'),
        ),
    ]
