# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0033_create_model_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='group',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
