# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0034_add_model_translation_to_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='goals.Group', verbose_name='Group'),
        ),
    ]
