# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0035_add_field_group_to_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Area code'),
        ),
    ]
