# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 09:23
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0037_increase_code_on_length_areatype_and_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progress',
            name='group',
        ),
        migrations.AddField(
            model_name='progress',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), blank=True, default=[], null=True, size=None, verbose_name='Groups'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
