# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0040_add_field_fiscal_year_on_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='year',
            field=models.IntegerField(default=9999, verbose_name='Year'),
            preserve_default=False,
        ),
    ]
