# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0041_alter_field_year_on_progress_diasallow_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
