# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0042_alter_field_year_on_progress_require_positive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='fiscal_year',
            field=models.CharField(blank=True, max_length=9, verbose_name='Fiscal year'),
        ),
    ]
