# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 12:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0044_alter_field_code_on_component_add_unique_constrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='goals.AreaType', verbose_name='Area type'),
            preserve_default=False,
        ),
    ]
