# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import goals.models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0045_alter_field_type_on_area_add_null_constrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='areatype',
            name='topojson',
            field=models.FileField(blank=True, null=True, upload_to=goals.models.area_type_topo_path, verbose_name='TopoJSON'),
        ),
    ]
