# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0047_add_theme_sector_and_sector_type_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Sector description'),
        ),
        migrations.AddField(
            model_name='sector',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Sector description'),
        ),
        migrations.AddField(
            model_name='sector',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/sectors/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sector',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/sectors/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Sector name'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Sector name'),
        ),
        migrations.AddField(
            model_name='sectortype',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sectortype',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='sectortype',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='sectortype',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='theme',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Theme description'),
        ),
        migrations.AddField(
            model_name='theme',
            name='description_sw',
            field=models.TextField(blank=True, null=True, verbose_name='Theme description'),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='goals/themes/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_sw',
            field=models.ImageField(blank=True, null=True, upload_to='goals/themes/images', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Theme name'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name_sw',
            field=models.CharField(max_length=255, null=True, verbose_name='Theme name'),
        ),
    ]
