# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-24 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0049_correct_label_for_field_sector_on_indicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Goal number'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Indicator number'),
        ),
        migrations.AlterField(
            model_name='target',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Target number'),
        ),
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together=set([('code', 'plan')]),
        ),
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together=set([('code', 'target', 'sector', 'theme')]),
        ),
        migrations.AlterUniqueTogether(
            name='target',
            unique_together=set([('code', 'goal')]),
        ),
    ]
