# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-25 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0050_use_unique_together_constrain_instead_of_unique_code_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='goals.Sector', verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='goals.Target', verbose_name='Target'),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='goals.Theme', verbose_name='Theme'),
        ),
    ]
