# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0053_add_field_theme_to_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='goal',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='goal',
            name='caption_sw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='theme',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='theme',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AddField(
            model_name='theme',
            name='caption_sw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='caption_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='caption_sw',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Caption'),
        ),
    ]
