# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-28 10:20
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0054_add_field_caption_to_goal_and_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='sectors_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=[], editable=False, null=True, size=None, verbose_name='Sectors ids'),
        ),
    ]
