# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 09:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def add_dummy_plan(apps, schema_editor):
    """Use a dummy area for progress with no areas
    """
    Plan = apps.get_model('goals', 'Plan')
    Theme = apps.get_model('goals', 'Theme')
    if Theme.objects.exists():
        plan = Plan()
        plan.name = 'Dummy Plan'
        plan.code = 'dummyplan'
        plan.save()
        Theme.objects.all().update(plan=plan)


def dummy(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0055_add_field_sectors_ids_to_indicator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='plans',
        ),
        migrations.AddField(
            model_name='theme',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='goals.Plan', verbose_name='Plans', null=True)
        ),
        migrations.RunPython(add_dummy_plan, reverse_code=dummy),
        migrations.AlterField(
            model_name='theme',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='goals.Plan', verbose_name='Plans')
        ),
    ]
