# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0056_add_field_plan_remove_field_plns_to_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='plan_id',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Plan ID'),
        ),
    ]
